# France Top 50 Playlist Analysis

## Data Cleaning Notebook

### Project
Audience Sensitivity, Content Compliance & Format Preference Analysis of France Top 50 Playlist

#### Objective
The objective of this notebook is to load, inspect, clean and validate the France Top 50 Playlist dataset before performing exploratory data analysis.

# Import Libraries

In [55]:
import pandas as pd
import numpy as np
import os

# Load the dataset

In [56]:
os.makedirs("../data/processed", exist_ok=True)
df = pd.read_csv("../data/france_top50_playlist.csv")

# Preview the dataset

In [57]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,LA RUE,No Limit & Gazo & Damso,72,225137,single,1,True,https://i.scdn.co/image/ab67616d0000b27384f245...
1,18-05-2024,2,C'est carré le S,Naps,74,201533,album,22,False,https://i.scdn.co/image/ab67616d0000b27348f7c1...
2,18-05-2024,3,Freestyle LVL UP 1,Ninho,76,114182,single,1,True,https://i.scdn.co/image/ab67616d0000b273fbe613...
3,18-05-2024,4,Bolide allemand,SDM,79,176746,album,15,True,https://i.scdn.co/image/ab67616d0000b273455e89...
4,18-05-2024,5,Freestyle LVL UP 2,Ninho,71,149064,single,1,True,https://i.scdn.co/image/ab67616d0000b27351f1cb...

# Dataset Overview

In [58]:
df.shape

(27800, 10)

In [59]:
df.columns

Index(['date', 'position', 'song', 'artist', 'popularity', 'duration_ms',
       'album_type', 'total_tracks', 'is_explicit', 'album_cover_url'],
      dtype='object')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  object
 1   position         27800 non-null  int64
 2   song             27799 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), int64(4), object(5)
memory usage: 1.9+ MB

In [61]:
df.describe()

           position    popularity    duration_ms  total_tracks
count  27800.000000  27800.000000   27800.000000  27800.000000
mean      25.500000     76.645108  185474.848165      8.999856
std       14.431129     11.570874   32436.845058      8.140060
min        1.000000      0.000000       0.000000      1.000000
25%       13.000000     71.000000  165586.000000      1.000000
50%       25.500000     75.000000  180000.000000     10.000000
75%       38.000000     83.000000  207733.000000     15.000000
max       50.000000    100.000000  547413.000000    119.000000

# Missing value Analysis

In [62]:
df.isnull().sum()

date               0
position           0
song               1
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
is_explicit        0
album_cover_url    0
dtype: int64

In [63]:
df[df['song'].isnull()]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
13001,02-02-2025,2,NaN,Lavern,0,0,single,5,False,https://i.scdn.co/image/ab67616d0000b273eb5e3a...

# Handling missing and invalid values

In [64]:
df = df.dropna(subset = ["song"])
df.isnull().sum()
df.shape

(27799, 10)

# Duplicate record analysis

In [65]:
duplicate_counts = df.duplicated().sum()
print(f"Total duplicates are : {duplicate_counts}")

Total duplicates are : 19

In [66]:
duplicates = df[df.duplicated(keep=False)]
duplicates

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
14350,01-03-2025,1,Pyramide,Werenoi,78,208405,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14351,01-03-2025,2,Petit génie,Jungeli & Imen Es & Alonzo,84,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
14352,01-03-2025,3,Ceux qu'on était,Pierre Garnier,82,174106,single,1,False,https://i.scdn.co/image/ab67616d0000b27398855c...
14355,01-03-2025,6,Beautiful Things,Benson Boone,100,180304,single,1,False,https://i.scdn.co/image/ab67616d0000b273f2a919...
14356,01-03-2025,7,MAMI WATA,Gazo & Tiakola,79,233240,album,12,True,https://i.scdn.co/image/ab67616d0000b2737dfe25...
14357,01-03-2025,8,Tu connais,Werenoi,74,169000,album,7,True,https://i.scdn.co/image/ab67616d0000b2737fed90...
14360,01-03-2025,11,Maudit,Werenoi,73,197568,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14361,01-03-2025,12,Houdini,Dua Lipa,95,185917,single,1,False,https://i.scdn.co/image/ab67616d0000b273001d57...
14364,01-03-2025,15,Temps en temps,Zola & Koba LaD,64,153649,album,15,True,https://i.scdn.co/image/ab67616d0000b273353d56...
14365,01-03-2025,16,greedy,Tate McRae,99,131872,single,1,True,https://i.scdn.co/image/ab67616d0000b27322fd80...
14366,01-03-2025,17,Chemin d'or,Werenoi,78,212093,album,19,True,https://i.scdn.co/image/ab67616d0000b2739d74d3...
14368,01-03-2025,19,Popcorn Salé,SANTA,78,238653,single,1,False,https://i.scdn.co/image/ab67616d0000b273215b11...
14379,01-03-2025,30,Ça mène à rien,PLK,75,198773,album,11,True,https://i.scdn.co/image/ab67616d0000b2735f47f0...
14388,01-03-2025,39,Solitaire,Werenoi,75,146440,album,14,True,https://i.scdn.co/image/ab67616d0000b27311b232...
14391,01-03-2025,42,La symphonie des éclairs,Zaho de Sagazan,73,198789,album,14,False,https://i.scdn.co/image/ab67616d0000b273e89bee...
14392,01-03-2025,43,Avec classe (feat. Aya Nakamura & Trinix),Corneille & Aya Nakamura & Trinix,74,186071,single,1,False,https://i.scdn.co/image/ab67616d0000b273bc7413...
14393,01-03-2025,44,Hypé,Aya Nakamura,76,157053,single,1,False,https://i.scdn.co/image/ab67616d0000b27343d858...
14394,01-03-2025,45,Whatever,Kygo & Ava Max,91,178273,single,1,False,https://i.scdn.co/image/ab67616d0000b2734d9144...
14398,01-03-2025,49,Bécane - A COLORS SHOW,Yamê,86,182440,single,1,True,https://i.scdn.co/image/ab67616d0000b2737dfba3...
14400,01-03-2025,1,Pyramide,Werenoi,78,208405,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14401,01-03-2025,2,Petit génie,Jungeli & Imen Es & Alonzo,84,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
14402,01-03-2025,3,Ceux qu'on était,Pierre Garnier,82,174106,single,1,False,https://i.scdn.co/image/ab67616d0000b27398855c...
14405,01-03-2025,6,Beautiful Things,Benson Boone,100,180304,single,1,False,https://i.scdn.co/image/ab67616d0000b273f2a919...
14406,01-03-2025,7,MAMI WATA,Gazo & Tiakola,79,233240,album,12,True,https://i.scdn.co/image/ab67616d0000b2737dfe25...
14407,01-03-2025,8,Tu connais,Werenoi,74,169000,album,7,True,https://i.scdn.co/image/ab67616d0000b2737fed90...
14410,01-03-2025,11,Maudit,Werenoi,73,197568,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14411,01-03-2025,12,Houdini,Dua Lipa,95,185917,single,1,False,https://i.scdn.co/image/ab67616d0000b273001d57...
14414,01-03-2025,15,Temps en temps,Zola & Koba LaD,64,153649,album,15,True,https://i.scdn.co/image/ab67616d0000b273353d56...
14415,01-03-2025,16,greedy,Tate McRae,99,131872,single,1,True,https://i.scdn.co/image/ab67616d0000b27322fd80...
14416,01-03-2025,17,Chemin d'or,Werenoi,78,212093,album,19,True,https://i.scdn.co/image/ab67616d0000b2739d74d3...
14418,01-03-2025,19,Popcorn Salé,SANTA,78,238653,single,1,False,https://i.scdn.co/image/ab67616d0000b273215b11...
14429,01-03-2025,30,Ça mène à rien,PLK,75,198773,album,11,True,https://i.scdn.co/image/ab67616d0000b2735f47f0...
14438,01-03-2025,39,Solitaire,Werenoi,75,146440,album,14,True,https://i.scdn.co/image/ab67616d0000b27311b232...
14441,01-03-2025,42,La symphonie des éclairs,Zaho de Sagazan,73,198789,album,14,False,https://i.scdn.co/image/ab67616d0000b273e89bee...
14442,01-03-2025,43,Avec classe (feat. Aya Nakamura & Trinix),Corneille & Aya Nakamura & Trinix,74,186071,single,1,False,https://i.scdn.co/image/ab67616d0000b273bc7413...
14443,01-03-2025,44,Hypé,Aya Nakamura,76,157053,single,1,False,https://i.scdn.co/image/ab67616d0000b27343d858...
14444,01-03-2025,45,Whatever,Kygo & Ava Max,91,178273,single,1,False,https://i.scdn.co/image/ab67616d0000b2734d9144...
14448,01-03-2025,49,Bécane - A COLORS SHOW,Yamê,86,182440,single,1,True,https://i.scdn.co/image/ab67616d0000b2737dfba3...

# Remove duplicate records

In [67]:
df = df.drop_duplicates()
print("Duplicate rows :",df.duplicated().sum())
print(df.shape)

Duplicate rows : 0
(27780, 10)

# Validate categorical columns

In [68]:
df["album_type"].unique()

array(['single', 'album', 'compilation'], dtype=object)

In [69]:
df["is_explicit"].unique()

array([ True, False])

# Validate daily playlist size

In [70]:
songs_per_day= df.groupby("date").size()
songs_per_day.value_counts()

50    553
81      1
49      1
Name: count, dtype: int64

In [71]:
songs_per_day[songs_per_day!=50]

date
01-03-2025    81
02-02-2025    49
dtype: int64

In [72]:
march1 = df[df["date"]=="2025-03-01"]
march1["position"].value_counts().sort_index()

Series([], Name: count, dtype: int64)

In [73]:
march1[march1.duplicated(subset=["position"],keep=False)].sort_values("position")

Empty DataFrame
Columns: [date, position, song, artist, popularity, duration_ms, album_type, total_tracks, is_explicit, album_cover_url]
Index: []

In [74]:
sorted(march1["position"].unique())

[]

In [75]:
march1 = march1.drop_duplicates(subset="position",keep="first")
other_days = df[df["date"]!="2025-03-01"]
df = pd.concat([other_days,march1], ignore_index=True)
df.sort_values(["date","position"]).reset_index(drop=True)

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,01-01-2025,1,Petit génie,Jungeli & Imen Es & Alonzo,81,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
1,01-01-2025,2,Casanova,Soolking & Gazo,83,189090,single,1,False,https://i.scdn.co/image/ab67616d0000b2735e90ed...
2,01-01-2025,3,FLASHBACK,Favé,76,176120,album,15,True,https://i.scdn.co/image/ab67616d0000b273bed20c...
3,01-01-2025,4,LAISSE MOI,KeBlack,79,168620,single,1,True,https://i.scdn.co/image/ab67616d0000b273ab5360...
4,01-01-2025,5,greedy,Tate McRae,97,131872,single,1,True,https://i.scdn.co/image/ab67616d0000b27322fd80...
...,...,...,...,...,...,...,...,...,...,...
27775,31-12-2024,46,Can't Hold Us (feat. Ray Dalton),Macklemore & Ryan Lewis & Macklemore & Ryan Lewis,85,258431,album,15,False,https://i.scdn.co/image/ab67616d0000b2732a6b36...
27776,31-12-2024,47,No love,Ninho,73,202186,album,16,True,https://i.scdn.co/image/ab67616d0000b27318d7ae...
27777,31-12-2024,48,Aïcha,Djadja & Dinaz,66,206684,single,1,False,https://i.scdn.co/image/ab67616d0000b27319ba7b...
27778,31-12-2024,49,Tu connais,Werenoi,59,169000,album,7,True,https://i.scdn.co/image/ab67616d0000b2737fed90...
27779,31-12-2024,50,Children of the Sky (a Starfield song),Imagine Dragons,75,207611,single,1,False,https://i.scdn.co/image/ab67616d0000b273900eb3...

In [76]:
songs_per_day = df.groupby("date").size()
songs_per_day.value_counts()

50    553
81      1
49      1
Name: count, dtype: int64

In [77]:
feb2 = df[df["date"]=="2025-02-02"]
feb2["position"].sort_values().tolist()

[]

# Convert date column

In [78]:
df["date"] = pd.to_datetime(df["date"], format="%d-%m-%Y")
df["date"].dtype

dtype('<M8[ns]')

In [79]:
df["date"].head()

0   2024-05-18
1   2024-05-18
2   2024-05-18
3   2024-05-18
4   2024-05-18
Name: date, dtype: datetime64[ns]

# Convert song duration to Minutes

In [80]:
df["duration_minutes"] = df["duration_ms"]/60000
df["duration_minutes"] = df["duration_minutes"].round(2)
df[["duration_minutes","duration_ms"]].head()

   duration_minutes  duration_ms
0              3.75       225137
1              3.36       201533
2              1.90       114182
3              2.95       176746
4              2.48       149064

In [81]:
df.to_csv("../data/france_top50_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## Data Cleaning Summary

### Cleaning Steps Performed

- Loaded the France Top 50 Playlist dataset.
- Inspected dataset structure using head(), info(), describe(), and shape.
- Identified one corrupted record with a missing song name, zero popularity, and zero duration. This record was removed.
- Detected and removed exact duplicate rows.
- Converted the "date" column to datetime format.
- Converted song duration from milliseconds to minutes.
- Validated daily playlist sizes.
- Investigated playlist anomalies:
  - One day contained 49 valid songs after removing a corrupted record.
  - One day contained multiple entries for the same playlist positions, indicating merged playlist snapshots. The first occurrence of each position was retained to restore the Top 50 playlist structure.